# Investimento na Bolsa de Valores 


Um investidor dispõe de € 50.000 para investir entre quatro possibilidades: bolsa X, bolsa Y, títulos X e títulos Y, pelo período de um ano. Pode ser investido no máximo em títulos X o valor de € 10.500 e, no máximo € 10.000 em títulos Y. O investimento na bolsa X implica um risco considerável, de modo que se decide não investir mais do que um quarto dos investimentos totais. O valor investido na bolsa Y deve ser pelo menos três vezes o valor investido na bolsa X. Além disto, o investidor requer que o investimento em títulos seja pelo menos a metade do valor investido nas bolsas. Os rendimentos líquidos anuais são estimados segundo é mostrado na tabela a seguir:

| Bolsa X | Bolsa Y | Titulos X | Titulos Y |
| --- | --- | --- | -- |
| 20% | 10% | 9% | 11%

## Definição do Problema 
<br>
X1: investimento em bolsa de valores X 
<br>
X2: investimento em bolsa de valores Y 
<br>
X3: investimento em títulos X 
<br>
X4: investimento em títulos Y 

### Restrições 
<br>
X1 + X2 + X3 + X4 ≤ 50000
<br>
X1 ≤ 12500
<br>
X3 ≤ 10500
<br>
X4 ≤ 10000
<br>
3·X1 - X2 ≤ 0
<br>
0.5·X1 + 0.5·X2 - X3 - X4 ≤ 0
<br>
Xi ≥ 0

### Função Objetivo 
Maximizar: 
<br>
Z = 0.2·X1 + 0.1·X2 + 0.09·X3 + 0.11·X4

In [26]:
from scipy.optimize import linprog_verbose_callback 
from scipy.optimize import linprog
import numpy as np 

In [35]:
c = [-0.2, -0.1, -0.09, -0.11]

A = [[1, 1, 1, 1], 
     [3, -1, 0, 0],
     [0.5, 0.5, -1, -1]]

b = [50000, 0, 0]

bounds = [(0, 12500),(0, None),(0, 10500),(0,10000)]

In [38]:
res = linprog(obj_func, coef_der, desi,  bounds=bounds ,method='simplex', callback=linprog_verbose_callback)
res


--------- Initial Tableau - Phase 1 ----------

[[      1.0000       1.0000       1.0000       1.0000       1.0000       0.0000       0.0000       0.0000       0.0000       0.0000   50000.0000]
 [      3.0000      -1.0000       0.0000       0.0000       0.0000       1.0000       0.0000       0.0000       0.0000       0.0000       0.0000]
 [      0.5000       0.5000      -1.0000      -1.0000       0.0000       0.0000       1.0000       0.0000       0.0000       0.0000       0.0000]
 [      1.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       1.0000       0.0000       0.0000   12500.0000]
 [      0.0000       0.0000       1.0000       0.0000       0.0000       0.0000       0.0000       0.0000       1.0000       0.0000   10500.0000]
 [      0.0000       0.0000       0.0000       1.0000       0.0000       0.0000       0.0000       0.0000       0.0000       1.0000   10000.0000]
 [     -0.2000      -0.1000      -0.0900      -0.1100       0.0000       0.0

     fun: -5866.666666666666
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([   0.        ,    0.        ,    0.        , 4166.66666667,
       3833.33333333,    0.        ])
  status: 0
 success: True
       x: array([ 8333.33333333, 25000.        ,  6666.66666667, 10000.        ])

## Conclusão

Utilizando o método, a melhor solução obtida foi investir: 
- 833.333 na bolsa X
- 25.000 na bolsa Y
- 6666.6666 no título X
- 10.000 no título Y 
<br>
E o lucro máximo seria: 3600.0