In [1]:
# COlocar a descricao do problema


In [74]:
from scipy.optimize import linprog
from scipy.optimize import linprog, linprog_verbose_callback

import numpy as np 

In [75]:
min_coef = [-0.2, -0.1, -0.09, -0.11]
coef_der = [[1,1,1,1], [0.5, 0.5, -1, -1], [3, -1, 0, 0]]
desi = [50000, 0, 0]

In [76]:
res = linprog(min_coef, A_ub=coef_der, bounds=[(0, 12500),(0, None),(0, 10500),(0,1000)], b_ub=desi ,method='simplex', callback=linprog_verbose_callback)
res


--------- Initial Tableau - Phase 1 ----------

[[      1.0000       1.0000       1.0000       1.0000       1.0000       0.0000       0.0000       0.0000       0.0000       0.0000   50000.0000]
 [      0.5000       0.5000      -1.0000      -1.0000       0.0000       1.0000       0.0000       0.0000       0.0000       0.0000       0.0000]
 [      3.0000      -1.0000       0.0000       0.0000       0.0000       0.0000       1.0000       0.0000       0.0000       0.0000       0.0000]
 [      1.0000       0.0000       0.0000       0.0000       0.0000       0.0000       0.0000       1.0000       0.0000       0.0000   12500.0000]
 [      0.0000       0.0000       1.0000       0.0000       0.0000       0.0000       0.0000       0.0000       1.0000       0.0000   10500.0000]
 [      0.0000       0.0000       0.0000       1.0000       0.0000       0.0000       0.0000       0.0000       0.0000       1.0000    1000.0000]
 [     -0.2000      -0.1000      -0.0900      -0.1100       0.0000       0.0

     fun: -3929.999999999999
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([15500.,     0.,     0.,  6750.,     0.,     0.])
  status: 0
 success: True
       x: array([ 5750., 17250., 10500.,  1000.])